### ISSUE TITLE
Remove jQuery from package.json dependencies

### ISSUE THREAD

**Issue by AlexKvazos** [mozilla/react-metrics-graphics#6]
Can we remove jquery from the dependencies? I do not see jquery being used internally by the package so I do not see why having jquery on node_modules would be useful.

**Comment by alexrussell** [comment]
I agree - in fact I have just chosen to *not* use this package because of the jQuery dependency.

If you still want to reference it, it should really go in either `peerDependencies` or `optionalDependencies` (though from the looks of the NPM docs on `optionalDependencies`, it's not a "suggests" key but a "try to install and if it fails don't worry" which is not what we want here - we want it to *not* install by default, but suggest also adding it to a project in order to use tooltips).

Additionally, I don't see `classnames` being used in the main code, but maybe I missed it.

**Comment by alexrussell** [comment]
> I agree - in fact I have just chosen to *not* use this package because of the jQuery dependency.

Sorry I've just reread this and it looks somewhat more aggressive than I meant it. I'm not trying to be an entitled open source consumer here, just saying that I, and probably many others, would prefer to keep jQuery out of our projects (as it happens, it's not even used (i.e. imported) in your source, so actually *would* stay out of the bundles as far as I can see), and being as you don't even use it directly, it seems silly to have it in as a dep.

**Comment by wlach** [comment]
Note that jquery is required by the underlying metricsgraphics package, but in general I agree.

**Comment by alexrussell** [comment]
That is true - but metrics-graphics already has jQuery in its peerDependencies, so will already warn the user that it needs to be installed. I think that including it in your own deps just because a dep of yours relies on it right now is too much. What if MG drops jQuery? Now you're 'depending' on it for nothing.

**Comment by alexrussell** [comment]
In fact, MG doesn't even need jQuery for the most part as far as I can see - only "[if] you wish to enable tooltips or use buttons". So it's arguable that they shouldn't even list it as a dep but more of a "suggests" or conditional dependency, which I don't think NPM currently handles.

**Comment by wlach** [comment]
Fixed with #10.
